"""JSON-Schema export for every published Forge model.

Phase 2 Stage B item 11-12: every Pydantic model that touches disk gets
a JSON Schema artifact under ``schemas/`` at the repo root. CI runs
``forge-schema-export --check`` (Stage A item 3) and fails on drift.

The descriptor schema published in Phase 1 lives under
``forge_mcp/descriptor/schema.json`` for backwards-compatibility with
the Phase-1 drift test; this module *also* publishes it under
``schemas/descriptor.schema.json`` so the published surface is uniform.
Both files are regenerated by ``--write`` and compared by ``--check``.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import TYPE_CHECKING

from forge_mcp.descriptor.schema import descriptor_json_schema
from forge_mcp.project.schemas import (
    AuditRecord,
    BoundaryStub,
    Edge,
    EdgeLayerFile,
    HistoryEvent,
    LockRecord,
    LockStoreFile,
    ProjectMetadata,
    RegionNode,
    SpecRecord,
    WorldRootNode,
)

if TYPE_CHECKING:
    from collections.abc import Iterator

REPO_ROOT: Path = Path(__file__).resolve().parents[2]
"""Filesystem root of the world_forge checkout."""

SCHEMAS_DIR: Path = REPO_ROOT / "schemas"
"""Published-schema directory; created on demand by ``--write``."""

LEGACY_DESCRIPTOR_SCHEMA_PATH: Path = REPO_ROOT / "forge_mcp" / "descriptor" / "schema.json"
"""Phase-1 drift artifact; preserved so the Phase-1 test keeps passing."""


def _pydantic_schema(
    model: type[object],
    name: str,
    title: str,
) -> tuple[str, dict[str, object]]:
    schema = model.model_json_schema()  # type: ignore[attr-defined]  # Pydantic surface
    if not isinstance(schema, dict):  # pragma: no cover  # defensive
        msg = f"{model!r}.model_json_schema() must return dict, got {type(schema)!r}"
        raise TypeError(msg)
    schema["title"] = title
    return name, schema


def iter_published_schemas() -> Iterator[tuple[str, dict[str, object]]]:
    """Yield ``(name, json_schema_dict)`` pairs for every published model.

    Names are bare schema-file stems (no extension, no directory).
    Order is deterministic so ``--write`` produces stable diffs.
    """
    yield "descriptor", descriptor_json_schema()
    yield _pydantic_schema(ProjectMetadata, "project", "ForgeProject")
    yield _pydantic_schema(WorldRootNode, "world_root", "ForgeWorldRootNode")
    yield _pydantic_schema(RegionNode, "region", "ForgeRegion")
    yield _pydantic_schema(Edge, "edge", "ForgeEdge")
    yield _pydantic_schema(EdgeLayerFile, "edge_layer", "ForgeEdgeLayerFile")
    yield _pydantic_schema(BoundaryStub, "boundary", "ForgeBoundary")
    yield _pydantic_schema(LockRecord, "lock", "ForgeLock")
    yield _pydantic_schema(LockStoreFile, "lock_store", "ForgeLockStore")
    yield _pydantic_schema(HistoryEvent, "history_event", "ForgeHistoryEvent")
    yield _pydantic_schema(SpecRecord, "spec", "ForgeSpec")
    yield _pydantic_schema(AuditRecord, "audit", "ForgeAudit")


def dump_schema_json(schema: dict[str, object]) -> str:
    """Serialize a JSON-Schema dict using Forge's canonical on-disk style.

    Sorted keys, two-space indent, ``ensure_ascii=False``, trailing
    newline. This matches the existing Phase-1 descriptor format and the
    Phase 2 Stage C ``dump_json`` helper (Stage C consolidates them).
    """
    return (
        json.dumps(
            schema,
            indent=2,
            sort_keys=True,
            separators=(",", ": "),
            ensure_ascii=False,
        )
        + "\n"
    )


def _expected_path(name: str) -> Path:
    return SCHEMAS_DIR / f"{name}.schema.json"


def _aliases_for(name: str) -> tuple[Path, ...]:
    """Return all on-disk paths a published schema must occupy.

    The descriptor schema is published in two places (see module
    docstring); everything else is single-pathed.
    """
    primary = _expected_path(name)
    if name == "descriptor":
        return (primary, LEGACY_DESCRIPTOR_SCHEMA_PATH)
    return (primary,)


def _write_all() -> int:
    SCHEMAS_DIR.mkdir(parents=True, exist_ok=True)
    written = 0
    for name, schema in iter_published_schemas():
        body = dump_schema_json(schema)
        for path in _aliases_for(name):
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(body, encoding="utf-8")
            written += 1
    return written


def _display(path: Path) -> str:
    try:
        return str(path.relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def _check_all() -> int:
    """Return zero if every committed schema matches its live model output."""
    drift: list[str] = []
    for name, schema in iter_published_schemas():
        body = dump_schema_json(schema)
        for path in _aliases_for(name):
            if not path.exists():
                drift.append(f"missing: {_display(path)}")
                continue
            on_disk = path.read_text(encoding="utf-8")
            if on_disk != body:
                drift.append(f"drift: {_display(path)}")
    if drift:
        message = (
            "forge-schema-export --check failed:\n  "
            + "\n  ".join(drift)
            + "\nRegenerate with `uv run forge-schema-export --write`."
        )
        sys.stderr.write(message + "\n")
        return 1
    return 0


def main(argv: list[str] | None = None) -> int:
    """``forge-schema-export`` CLI entry point.

    ``--write`` regenerates the committed schemas; ``--check`` (the CI
    mode) returns non-zero on any drift.
    """
    parser = argparse.ArgumentParser(
        prog="forge-schema-export",
        description="Generate or verify Forge's published JSON Schemas.",
    )
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument(
        "--write",
        action="store_true",
        help="(re)generate schemas/ and the legacy descriptor artifact",
    )
    mode.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if any committed schema has drifted",
    )
    args = parser.parse_args(argv)
    if args.write:
        n = _write_all()
        print(f"wrote {n} schema files under {SCHEMAS_DIR.relative_to(REPO_ROOT)}/")  # noqa: T201
        return 0
    return _check_all()


if __name__ == "__main__":  # pragma: no cover  # CLI entry point
    raise SystemExit(main())
